services:

  web:
    container_name: weather-web
    build:
      context: ../web
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - '5173:5173'
    networks:
      - web-weather-network

networks:
  web-weather-network:
    external: 
      name: weather-network